
package com.team.generatedCode;

import javax.xml.ws.Endpoint;

import com.team.webservice.interfaces.SimpleServiceImpl;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2013-01-02T11:09:18.172+02:00
 * Generated source version: 2.6.4
 * 
 */
 
public class SimpleService_P1_Server{

    protected SimpleService_P1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SimpleServiceImpl();
        String address = "http://localhost:8080/ss/p1";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SimpleService_P1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
