package com.team.generatedCode;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2013-01-02T11:09:18.176+02:00
 * Generated source version: 2.6.4
 * 
 */
@WebServiceClient(name = "SimpleService", 
                  wsdlLocation = "src/main/resources/SimpleService.wsdl",
                  targetNamespace = "http://www.example.org/SimpleService/") 
public class SimpleService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/SimpleService/", "SimpleService");
    public final static QName P1 = new QName("http://www.example.org/SimpleService/", "p1");
    static {
        URL url = SimpleService_Service.class.getResource("src/main/resources/SimpleService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SimpleService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/main/resources/SimpleService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SimpleService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SimpleService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SimpleService
     */
    @WebEndpoint(name = "p1")
    public SimpleService getP1() {
        return super.getPort(P1, SimpleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleService
     */
    @WebEndpoint(name = "p1")
    public SimpleService getP1(WebServiceFeature... features) {
        return super.getPort(P1, SimpleService.class, features);
    }

}
